export const projects = [
  {
    title: 'Movie App',
    description: 'Full stack application with login and user registration, search, list and save favorite movies',
      image: '/images/3.png',
      tags: ['React', 'Node', 'Express', 'MongoDB', 'JWT'],
    code: 'https://github.com/LCisternas/OMDB',
    live: 'https://movie-app-lcisternas.netlify.app',
    id: 2,
  },
  {
    title: 'Gatsby + Strapi',
    description: 'Application made with Gastby - React on the front, and using the Strapi CMS deployed in heroku for the entire database',
    image: '/images/2.png',
    tags: ['React', 'Gastby', 'Strapi'],
    code: 'https://github.com/LCisternas/gatsby-strapi',
    live: 'https://gatsby-strapi-bienes-raices.netlify.app',
    id: 1,
  },
  {
    title: 'Product Hunt Clone',
    description: 'Full stack application that mimics the Product Hunt website, made with React with Next.js on the front, and Firebase for user authentication and the entire database',
      image: '/images/1.png',
      tags: ['React', 'Next.js', 'Firebase'],
    code: 'https://github.com/LCisternas/producthunt-next.js',
    live: 'https://producthunt-next-js.vercel.app',
    id: 0,
  },
  {
    title: 'Pokepedia',
    description: 'Application made with react and styled component that consumes the pokeapi API and lists pokemons according to their category',
    image: '/images/4.png',
    tags: ['React', 'useContext'],
    code: 'https://github.com/LCisternas/pokepedia',
    live: 'https://pokepedia-lcisternas.netlify.app',
    id: 3,
  },
];